specification = "1.1"

code = "summa"
name = "Saskaiti skaitļus!"

authors = ["Krišjānis Petručeņa"]
tags = ["math"]

type = "simple" # simple (default checker) / checker / interactive

time = 1.0 # seconds
memory = 64 # MB

difficulty = 1 # 1-5

