specification = "2.0"

task_name = "Saskaiti skaitļus!"

[metadata]
problem_tags = ["math"]
difficulty_1_to_5 = 1
task_authors = ["Krišjānis Petručeņa"]

[constraints]
memory_megabytes = 64
cpu_time_seconds = 1.0